
// #### Transaction
// * `userEmail` (Account Holder Email)
// * `amount` (Number of tokens in transaction)
// * `type` (Possible values: ['send', 'receive'])
// * `createdAt` (Transaction creation date)

// A transaction can only be associated with one user. A user can be associated with many transactions.  
// Feel free to replace the userEmail field with a userId field generated by your data storage method of choice.  
// In this repo are a few sample data file:
